version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    env_file:
      - .env  # Carrega o .env da raiz para o banco
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - lease_network

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - lease_network

  backend:
    build: 
      context: ./Lease-Management-Backend
    container_name: lease_backend
    restart: always
    depends_on:
      - mongodb
    ports:
      - "2000:2000"
    env_file:
      - ./Lease-Management-Backend/.env  # Carrega o .env do backend
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/
    volumes:
      - ./Lease-Management-Backend:/app
    networks:
      - lease_network

  frontend:
    build:
      context: ./lease-management-frontend
    container_name: lease_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./lease-management-frontend:/app
    environment:
      - NODE_ENV=development
    networks:
      - lease_network


networks:
  lease_network:
    driver: bridge

volumes:
  mongo_data:
